#ifndef MYOS__ATA_H
#define MYOS__ATA_H

#define ATA_IO_REGISTER_DATA 0
#define ATA_IO_REGISTER_ERROR 1
#define ATA_IO_REGISTER_FEATURES 1
#define ATA_IO_REGISTER_SECTOR_COUNT 2
#define ATA_IO_REGISTER_SECTOR_NUMBER_0 3
#define ATA_IO_REGISTER_SECTOR_NUMBER_1 4
#define ATA_IO_REGISTER_SECTOR_NUMBER_2 5
#define ATA_IO_REGISTER_DRIVE 6
#define ATA_IO_REGISTER_STATUS 7
#define ATA_IO_REGISTER_COMMAND 7

#define ATA_CONTROL_REGISTER_ALT_STATUS 0
#define ATA_CONTROL_REGISTER_DEV_CONTROL 0
#define ATA_CONTROL_REGISTER_DRIVE_ADDR 1

#define ATA_STATUS_BUS_FLOATING 0xff

// For register ATA_IO_REGISTER_DRIVE_HEAD
#define ATA_USE_SLAVE_BIT 0x10
#define ATA_USE_LBA_BIT 0x40

// For register ATA_IO_REGISTER_STATUS, ATA_CONTROL_REGISTER_ALT_STATUS
#define ATA_STATUS_ERR      0x01
#define ATA_STATUS_IDX      0x02
#define ATA_STATUS_CORR     0x04
#define ATA_STATUS_DRQ      0x08
#define ATA_STATUS_SRV      0x10
#define ATA_STATUS_DF       0x20
#define ATA_STATUS_RDY      0x40
#define ATA_STATUS_BSY      0x80

// For register ATA_IO_REGISTER_COMMAND
#define ATA_COMMAND_IDENTIFY 0xEC
#define ATA_COMMAND_READ_SECTORS_EXT 0x24
#define ATA_COMMAND_WRITE_SECTORS_EXT 0x34

#define ATA_IDENTIFY_SIZE 256

#endif //MYOS__ATA_H
